//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPM_QLyHoSoSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBangDiem
    {
        public string MaBangDiem { get; set; }
        public string MaMonHoc { get; set; }
        public Nullable<double> DiemChuyenCan { get; set; }
        public Nullable<double> DiemThuongXuyen { get; set; }
        public Nullable<double> DiemThi { get; set; }
    
        public virtual DSBangDiem DSBangDiem { get; set; }
        public virtual DSMonHoc DSMonHoc { get; set; }
    }
}
